name: Jekyll Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Bundler
        run: |
          gem install bundler

      - name: Update http_parser.rb gem
        run: |
          bundle update http_parser.rb

      - name: Build the Jekyll site using Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/srv/jekyll \
            -v /usr/local/bundle:/usr/local/bundle \
            -p 4000:4000 \
            jekyll/builder:4.2.0 \
            jekyll build --trace

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './_site'
