name: Jekyll Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write  # Necessário para OIDC

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.4'
        bundler: '2.4.22'

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          vendor/bundle
          ~/.gem
          tmp/cache
        key: ${{ runner.os }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Build with Jekyll
      run: |
        JEKYLL_ENV=production bundle exec jekyll build --trace

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        full_commit_message: "Deploy via GitHub Actions $(date '+%Y-%m-%d %H:%M:%S')"
