name: Jekyll Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # This allows write access to the repository contents
      pages: write     # This allows write access to GitHub Pages

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.0'

    - name: Install Bundler
      run: |
        gem install bundler:2.3.10  # Specify a compatible version of Bundler
        bundler -v  # Verify bundler version

    - name: Cache Ruby gems
      uses: actions/cache@v3  # Updated version
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Install dependencies
      run: bundle install --verbose

    - name: Build Jekyll site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: './_site'
        user_name: 'github-actions'
        user_email: 'github-actions@github.com'
